name: "CI - Tests Automatisés avec IA"
    
on: 
  push:
    branches: 
      - sgoales
jobs:
  cypress-run:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        groups:
        - name: apibank
          specs: |
            cypress/tests/api/api-bankaccounts.spec.ts
            cypress/tests/api/api-banktransfers.spec.ts
        - name: apiuser
          specs: |
            cypress/tests/api/api-users.spec.ts
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc" 
          
      - name: Cypress run (${{ matrix.groups.name }} suites) # Installe aussi les dépendances npm
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: http://localhost:3000
          build: npm run build
      - name: Install Hurl
        run: curl -L https://github.com/Orange-OpenSource/hurl/releases/latest/download/hurl-linux-x86_64.tar.gz |
      - name: Run Hurl Tests
        run: hurl -test -output results.json tests/*.hurl
        with:
          start: npm run start
          wait-on: http://localhost:3000
          build: npm run build
      - name: Upload Results
        uses: actions/upload-artifact@v5
        with:
          name: hurl-test-results
          path: results.json