name: "CI - Tests Automatisés avec IA"
    
on: 
  push:
    branches: 
      - sgoales
jobs:
  cypress-run:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        groups:
        - name: apibank
          specs: |
            cypress/tests/api/api-bankaccounts.spec.ts
            cypress/tests/api/api-banktransfers.spec.ts
        - name: apiuser
          specs: |
            cypress/tests/api/api-users.spec.ts
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc" 
          
      - name: Install Hurl
        run: |
          curl -sSL https://pkg.hurl.dev/hurl.pubkey | sudo tee /usr/share/keyrings/hurl-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/hurl-archive-keyring.gpg] https://pkg.hurl.dev/deb/ stable main" | sudo tee /etc/apt/sources.list.d/hurl.list
          sudo apt-get update
          sudo apt-get install -y hurl
      - name: Run Hurl Tests
        run: hurl -test -output results.json tests/*.hurl
      - name: Upload Results
        uses: actions/upload-artifact@v5
        with:
          name: hurl-test-results
          path: results.json