name: "CI - Tests Automatisés avec IA"
    
on: 
  push:
    branches: 
      - sgoales
jobs:
  cypress-run:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        groups:
        - name: apibank
          specs: |
            cypress/tests/api/api-bankaccounts.spec.ts
            cypress/tests/api/api-banktransfers.spec.ts
        - name: apiuser
          specs: |
            cypress/tests/api/api-users.spec.ts
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc" 
          
      - name: Install Hurl
        run: npm install --save-dev @orangeopensource/hurl
      - name: Run Hurl Tests
        run: hurl -test -output results.json tests/*.hurl
      - name: Upload Results
        uses: actions/upload-artifact@v5
        with:
          name: hurl-test-results
          path: results.json